name: publish to nuget
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0
    - name: Build
      run: dotnet build -c Release
    - name: Package
      run: dotnet pack -c Release -o .
    - name: Publish
      run: dotnet nuget push **/*.nupkg -s 'https://api.nuget.org/v3/index.json' -k '${{ secrets.NUGET_API_KEY }}'
